import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { categoryMeta } from "@/lib/site";
import { getAllPosts, getAllTags } from "@/lib/content";

export const metadata: Metadata = { title: "Topics", description: "Browse Gulshan Kumar's writing by topic, category, and technology." };

export default function TopicsPage() { const posts = getAllPosts(); const tags = getAllTags(); return <><section className="page-hero"><div className="container"><div className="eyebrow">The index</div><h1>Follow the<br /><span className="serif">threads.</span></h1><p>Broad categories give the archive shape. Specific tags make it useful when you are looking for a particular idea, tool, or technology.</p></div></section><section className="section"><div className="container"><div className="topic-intro"><div><div className="eyebrow">Six working categories</div><h2 className="display">Big questions,<br />small notes.</h2></div><p>{posts.length} published pieces, connected by the questions I keep returning to.</p></div><div className="topic-list" style={{ marginTop: "2rem" }}>{Object.values(categoryMeta).map((topic, index) => <Link className="topic-list-card" href={`/topics/${topic.slug}`} key={topic.slug}><div className="topic-card-number"><span>0{index + 1}</span><ArrowUpRight size={16} /></div><h2>{topic.name}</h2><p>{topic.description}</p><div className="tag-cloud">{Array.from(new Set(posts.filter((post) => post.category === topic.slug).flatMap((post) => post.tags))).slice(0, 5).map((tag) => <span className="tag" key={tag}>{tag}</span>)}</div></Link>)}</div></div></section><section className="section soft-section"><div className="container"><div className="section-heading"><div><div className="eyebrow">The vocabulary</div><h2>Specific tools.<br />Useful handles.</h2></div><p>Tags stay intentionally focused: a few relevant technologies per article, not a cloud of keywords.</p></div><div className="tag-cloud" style={{ maxWidth: "760px", margin: 0 }}>{tags.map((tag) => <span className="tag" key={tag}>{tag}</span>)}</div></div></section></>; }
